protocol: 'https'
certificate:
  pem: 'ca-cert.pem'
  key: 'ca-key.pem'
timeout: '10s'
serve_addr_proxy: ':8888'
serve_addr_burst: ':8000'
db:
  host: 'localhost'
  port: '27051'
  timeout: '10s'
  database_name: 'requests'
  collection_name: 'requests'